theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
    math_engine: katex
    
<!-- MathJax -->
<script type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
